# playbook to configure httpd proxy on container
# Paul Armstrong
# Red Hat
# parmstro@redhat.com
# 2017-06-28
#
- hosts: localhost
  vars:
    httpd_port: 80
    httpd_ssl_port: 443
    proxy_target_fqdn: idm.parmstrong.ca
    proxy_referer_fqdn: someserver.parmstrong.ca
    proxy_referer_fqdn_match: someserver\.parmstrong\.ca

  remote_user: root

  tasks:
  - name: Configure httpd server
    blockinfile:
      path: /etc/httpd/conf.d/ssl.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      insertbefore: "</VirtualHost>"
      content: |
        # add the following directives
        SSLProxyEngine On
        Header add Referer {{ proxy_target_fqdn }}
        RequestHeader edit Referer ^https://{{ proxy_referer_fqdn_match }}/ https://{{ proxy_target_fqdn }}/
        # RequestHeader set Front-End-Https "On"
        ProxyPass / https://{{ proxy_target_fqdn }}/
        ProxyPassReverse / https://{{ proxy_target_fqdn }}/
        ProxyPassReverseCookieDomain {{ proxy_target_fqdn }} {{ proxy_referer_fqdn }}
